#!/usr/bin/env python3
"""Probe the installed PyTorch ROCm version and write rocm_env.bat / rocm_env.sh.

bitsandbytes needs BNB_ROCM_VERSION to match the ROCm SDK bundled with the PyTorch wheel
(e.g. 714 for ROCm 7.14, 715 for 7.15). run_fizgig_rocm.bat and run_fizgig_rocm.sh source these.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
OUT_BAT = SCRIPT_DIR / "rocm_env.bat"
OUT_SH = SCRIPT_DIR / "rocm_env.sh"
DEFAULT_BNB_LINUX = "714"  # libbitsandbytes_rocm714.so - matches stable repo.amd.com torch
DEFAULT_BNB_WIN = "715"  # Windows 0xDELUXA wheel / pinned multi-arch torch (+rocm7.15)


def _linux_rocm_core_path() -> Path:
    for p in sorted((SCRIPT_DIR / "venv" / "lib").glob("python*/site-packages/_rocm_sdk_core")):
        if p.is_dir():
            return p.resolve()
    raise FileNotFoundError("_rocm_sdk_core not found under venv/lib/")


def bnb_rocm_version_from_torch() -> str:
    import torch

    rocm = getattr(torch.version, "rocm", None)
    if rocm:
        m = re.match(r"(\d+)\.(\d+)", str(rocm))
        if m:
            major = int(m.group(1))
            minor = int(m.group(2))
            # bitsandbytes wheels ship 64/70/71/714/72 — ignore ROCm 10.x style tags.
            if major >= 7 and major <= 9:
                return f"{major}{minor}"

    m = re.search(r"\+rocm(\d+)\.(\d+)", torch.__version__, re.I)
    if m:
        major = int(m.group(1))
        minor = int(m.group(2))
        if major >= 7 and major <= 9:
            return f"{major}{minor}"

    hip = getattr(torch.version, "hip", None)
    if hip:
        m = re.match(r"(\d+)\.(\d+)", str(hip))
        if m:
            major = int(m.group(1))
            minor = int(m.group(2))
            if major >= 7 and major <= 9:
                return f"{major}{minor}"

    raise RuntimeError(
        f"could not parse ROCm 7.x version from torch {torch.__version__!r} "
        f"(rocm={rocm!r}, hip={hip!r})"
    )


def _bitsandbytes_rocm_lib(bnb_suffix: str) -> Path | None:
    try:
        import bitsandbytes
    except Exception:
        return None
    so = Path(bitsandbytes.__file__).resolve().parent / f"libbitsandbytes_rocm{bnb_suffix}.so"
    return so if so.is_file() else None


def main() -> int:
    is_linux = sys.platform.startswith("linux")
    default_bnb = DEFAULT_BNB_LINUX if is_linux else DEFAULT_BNB_WIN
    try:
        probed = bnb_rocm_version_from_torch()
        import torch
        src = f"torch {torch.__version__}"
        bnb = probed
        so = _bitsandbytes_rocm_lib(bnb)
        if so is None and is_linux and probed != DEFAULT_BNB_LINUX:
            fallback = _bitsandbytes_rocm_lib(DEFAULT_BNB_LINUX)
            if fallback is not None:
                print(
                    f"WARN: libbitsandbytes_rocm{bnb}.so missing; "
                    f"using BNB_ROCM_VERSION={DEFAULT_BNB_LINUX} ({fallback.name})",
                    file=sys.stderr,
                )
                bnb = DEFAULT_BNB_LINUX
                so = fallback
        if so is None:
            print(
                f"WARN: no matching libbitsandbytes_rocm*.so for ROCm {probed}; "
                f"using BNB_ROCM_VERSION={default_bnb}",
                file=sys.stderr,
            )
            bnb = default_bnb
        elif is_linux and probed == DEFAULT_BNB_LINUX:
            src = f"{src} (Linux ROCm 7.14 / bnb {bnb})"
        else:
            src = f"{src} (bnb {bnb} / {so.name})"
    except Exception as exc:
        print(f"WARN: {exc}; using default BNB_ROCM_VERSION={default_bnb}")
        bnb = default_bnb
        src = "default (install probe failed)"

    rocm_core_win = SCRIPT_DIR / "venv" / "Lib" / "site-packages" / "_rocm_sdk_core"
    try:
        rocm_core_linux = _linux_rocm_core_path()
    except FileNotFoundError:
        rocm_core_linux = None

    if rocm_core_win.is_dir():
        core = rocm_core_win.resolve()
        bat_lines = [
            "@echo off",
            "REM Auto-generated by write_rocm_env.py - re-run installer to refresh.",
            f"REM Detected from: {src}",
            f'set "BNB_ROCM_VERSION={bnb}"',
            f'set "ROCM_PATH={core}"',
            f'set "HIP_PATH={core}"',
            "",
        ]
        OUT_BAT.write_text("\r\n".join(bat_lines), encoding="utf-8")
        print(f"Wrote {OUT_BAT.name}: BNB_ROCM_VERSION={bnb}  ({src})")

    if rocm_core_linux is not None:
        sh_lines = [
            "# Auto-generated by write_rocm_env.py - re-run installer to refresh.",
            f"# Detected from: {src}",
            f'export BNB_ROCM_VERSION="{bnb}"',
            f'export ROCM_PATH="{rocm_core_linux}"',
            f'export HIP_PATH="{rocm_core_linux}"',
            "",
        ]
        OUT_SH.write_text("\n".join(sh_lines), encoding="utf-8")
        print(f"Wrote {OUT_SH.name}: BNB_ROCM_VERSION={bnb}  ({src})")

    if not rocm_core_win.is_dir() and rocm_core_linux is None:
        print("WARN: _rocm_sdk_core not found - no rocm_env files written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
