#!/usr/bin/env python3
"""Probe the installed PyTorch ROCm version and write rocm_env.bat for run_fizgig_rocm.bat.

bitsandbytes on Windows needs BNB_ROCM_VERSION to match the ROCm SDK bundled with the
PyTorch wheel (e.g. 715 for ROCm 7.15). The comfyui-rocm / nightly install path ships
rocm7.15 today, but this script reads whatever is actually installed so the launcher
stays in sync after upgrades.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
OUT = SCRIPT_DIR / "rocm_env.bat"
DEFAULT_BNB = "715"  # matches 0xDELUXA bitsandbytes_win_rocm wheel (rocm7.15)


def bnb_rocm_version_from_torch() -> str:
    import torch

    rocm = getattr(torch.version, "rocm", None)
    if rocm:
        m = re.match(r"(\d+)\.(\d+)", str(rocm))
        if m:
            return f"{m.group(1)}{int(m.group(2))}"

    m = re.search(r"\+rocm(\d+)\.(\d+)", torch.__version__, re.I)
    if m:
        return f"{m.group(1)}{int(m.group(2))}"

    hip = getattr(torch.version, "hip", None)
    if hip:
        m = re.match(r"(\d+)\.(\d+)", str(hip))
        if m:
            return f"{m.group(1)}{int(m.group(2))}"

    raise RuntimeError(
        f"could not parse ROCm version from torch {torch.__version__!r} "
        f"(rocm={rocm!r}, hip={hip!r})"
    )


def main() -> int:
    try:
        bnb = bnb_rocm_version_from_torch()
        import torch
        src = f"torch {torch.__version__}"
    except Exception as exc:
        print(f"WARN: {exc}; using default BNB_ROCM_VERSION={DEFAULT_BNB}")
        bnb = DEFAULT_BNB
        src = "default (install probe failed)"

    rocm_core = (SCRIPT_DIR / "venv" / "Lib" / "site-packages" / "_rocm_sdk_core").resolve()

    lines = [
        "@echo off",
        "REM Auto-generated by install_fizgig_rocm.bat / write_rocm_env.py — re-run installer to refresh.",
        f"REM Detected from: {src}",
        f'set "BNB_ROCM_VERSION={bnb}"',
        f'set "ROCM_PATH={rocm_core}"',
        f'set "HIP_PATH={rocm_core}"',
        "",
    ]
    OUT.write_text("\r\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.name}: BNB_ROCM_VERSION={bnb}  ({src})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
