#!/usr/bin/env python3
"""Probe the installed PyTorch ROCm version and write rocm_env.bat / rocm_env.sh.

bitsandbytes needs BNB_ROCM_VERSION to match the ROCm SDK bundled with the PyTorch wheel
(e.g. 714 for ROCm 7.14, 715 for 7.15). run_fizgig_rocm.bat and run_fizgig_rocm.sh source these.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
OUT_BAT = SCRIPT_DIR / "rocm_env.bat"
OUT_SH = SCRIPT_DIR / "rocm_env.sh"
DEFAULT_BNB_LINUX = "714"  # libbitsandbytes_rocm714.so — matches stable repo.amd.com torch
DEFAULT_BNB_WIN = "715"  # Windows 0xDELUXA wheel / nightly torch stack


def _linux_rocm_core_path() -> Path:
    for p in sorted((SCRIPT_DIR / "venv" / "lib").glob("python*/site-packages/_rocm_sdk_core")):
        if p.is_dir():
            return p.resolve()
    raise FileNotFoundError("_rocm_sdk_core not found under venv/lib/")


def bnb_rocm_version_from_torch() -> str:
    import torch

    rocm = getattr(torch.version, "rocm", None)
    if rocm:
        m = re.match(r"(\d+)\.(\d+)", str(rocm))
        if m:
            return f"{m.group(1)}{int(m.group(2))}"

    m = re.search(r"\+rocm(\d+)\.(\d+)", torch.__version__, re.I)
    if m:
        return f"{m.group(1)}{int(m.group(2))}"

    hip = getattr(torch.version, "hip", None)
    if hip:
        m = re.match(r"(\d+)\.(\d+)", str(hip))
        if m:
            return f"{m.group(1)}{int(m.group(2))}"

    raise RuntimeError(
        f"could not parse ROCm version from torch {torch.__version__!r} "
        f"(rocm={rocm!r}, hip={hip!r})"
    )


def main() -> int:
    is_linux = sys.platform.startswith("linux")
    default_bnb = DEFAULT_BNB_LINUX if is_linux else DEFAULT_BNB_WIN
    try:
        probed = bnb_rocm_version_from_torch()
        import torch
        src = f"torch {torch.__version__}"
        if is_linux:
            if probed != DEFAULT_BNB_LINUX:
                print(
                    f"ERROR: torch reports ROCm SDK {probed} but Linux requires "
                    f"{DEFAULT_BNB_LINUX} (libbitsandbytes_rocm714.so). "
                    f"Re-run ./install_fizgig_rocm_linux.sh (ROCm 7.14 pin).",
                    file=sys.stderr,
                )
                return 1
            bnb = DEFAULT_BNB_LINUX
            src = f"{src} (Linux ROCm 7.14 / bnb {bnb})"
        else:
            bnb = probed
    except Exception as exc:
        print(f"WARN: {exc}; using default BNB_ROCM_VERSION={default_bnb}")
        bnb = default_bnb
        src = "default (install probe failed)"

    rocm_core_win = SCRIPT_DIR / "venv" / "Lib" / "site-packages" / "_rocm_sdk_core"
    try:
        rocm_core_linux = _linux_rocm_core_path()
    except FileNotFoundError:
        rocm_core_linux = None

    if rocm_core_win.is_dir():
        core = rocm_core_win.resolve()
        bat_lines = [
            "@echo off",
            "REM Auto-generated by write_rocm_env.py — re-run installer to refresh.",
            f"REM Detected from: {src}",
            f'set "BNB_ROCM_VERSION={bnb}"',
            f'set "ROCM_PATH={core}"',
            f'set "HIP_PATH={core}"',
            "",
        ]
        OUT_BAT.write_text("\r\n".join(bat_lines), encoding="utf-8")
        print(f"Wrote {OUT_BAT.name}: BNB_ROCM_VERSION={bnb}  ({src})")

    if rocm_core_linux is not None:
        sh_lines = [
            "# Auto-generated by write_rocm_env.py — re-run installer to refresh.",
            f"# Detected from: {src}",
            f'export BNB_ROCM_VERSION="{bnb}"',
            f'export ROCM_PATH="{rocm_core_linux}"',
            f'export HIP_PATH="{rocm_core_linux}"',
            "",
        ]
        OUT_SH.write_text("\n".join(sh_lines), encoding="utf-8")
        print(f"Wrote {OUT_SH.name}: BNB_ROCM_VERSION={bnb}  ({src})")

    if not rocm_core_win.is_dir() and rocm_core_linux is None:
        print("WARN: _rocm_sdk_core not found — no rocm_env files written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
